src/AppBundle/Entity/PricesTrait.php
<?php

namespace AppBundle\Entity;

trait PricesTrait
{

    /**
     * @var integer
     * @ORM\Column(type="integer", nullable=true)
     */
    private $priceAccommodation;

    /**
     * @var integer
     * @ORM\Column(type="integer", nullable=true)
     */
    private $priceLifeCost;

    /**
     * @return int
     */
    public function getPriceAccommodation()
    {
        return $this->priceAccommodation;
    }

    /**
     * @param int $priceAccommodation
     * @return $this
     */
    public function setPriceAccommodation($priceAccommodation)
    {
        $this->priceAccommodation = $priceAccommodation;

        return $this;
    }

    /**
     * @return int
     */
    public function getPriceLifeCost()
    {
        return $this->priceLifeCost;
    }

    /**
     * @param int $priceLifeCost
     * @return $this
     */
    public function setPriceLifeCost($priceLifeCost)
    {
        $this->priceLifeCost = $priceLifeCost;

        return $this;
    }

    /**
     * @return int
     */
    public function getTotalPrices()
    {
        return $this->priceLifeCost + $this->priceAccommodation;
    }


}

src/AppBundle/Controller/VignetteController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Destination;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * @Route("/vignette")
 */
class VignetteController extends Controller
{

    /**
     * @Route("/{slug}", name="vignette")
     * @param Destination $destination
     * @return Response
     */
    public function getAction(Destination $destination)
    {
        return $this->render('AppBundle:Vignette:destination.html.twig',
            [
                'destination'    => $destination,
            ]);
    }

}

src/AppBundle/Resources/views/Vignette/destination.html.twig
<div class="col-lg-4 col-md-6 col-sm-6 containerPadding15">
    {% include 'AppBundle:Vignette:destinationContent.html.twig' %}
</div>

src/AppBundle/Resources/views/Vignette/destinationContent.html.twig
{% set bannerAssetURL = image_banner_destinations_path ~ destination.slug ~ '.JPG' %}
{% set bannerUrl = image_banner_default %}
{% if bannerAssetURL|asset_exists %}
    {% set bannerUrl = bannerAssetURL %}
{% endif %}

{% if currentDestinationSlug is not defined %}
    {% set currentDestinationSlug = '' %}
{% endif %}

{% if currentDestinationSlug != destination.slug %}
<a href="{{ path('destination', {'slug' : destination.slug }) }}" class="vignetteDestination" data-destinationid="{{ destination.id }}">
    {% endif %}

    <img class="img-responsive img-thumbnail" src="{{ asset(bannerUrl) }}"
         alt="{{ destination.name }}">

    <h4 class="vignetteTitle">
        {{ destination.name }}
        <span class="label label-success pull-right vignetteFontSize">
                {% if destinationPrices is defined %}
                    {{ destinationPrices }} &euro; / jour
                {% else %}
                    {{ destination.totalPrices }} &euro; / jour
                {% endif %}
            </span>

    </h4>

    {% if currentDestinationSlug != destination.slug %}
</a>
{% endif %}